/* Rutas de las imágenes y de los CV (antes estaban incrustados en base64). */
const IMG = {
  "diners_confidential": "img/diners-confidential.webp",
  "pablo_dashboard": "img/pablo_dashboard.jpeg",
  "pablo_hallazgos": "img/pablo_hallazgos.webp",
  "pablo_vistas": "img/pablo_vistas.webp",
  "certezia_arquetipos": "img/certezia_arquetipos.webp",
  "certezia_bmcs": "img/certezia_bmcs.webp",
  "certezia_preguntas": "img/certezia_preguntas.webp",
  "certezia_errores": "img/certezia_errores.webp",
  "certezia_uikit": "img/certezia_uikit.webp",
  "certezia_tam-sam-som": "img/certezia_tam-sam-som.jpg",
  "certezia_flujo-final": "img/certezia_flujo-final.webp",
  "certezia_flujo-redisenado": "img/certezia_flujo-redisenado.webp",
  "certezia_hero": "img/certezia_hero.webp",
  "certezia_problema": "img/certezia_problema.webp",
  "certezia_vista-prototipo": "img/certezia_vista-prototipo.webp",
  "certezia_vista-testing": "img/certezia_vista-testing.webp",
  "eliana": "img/eliana.webp",
  "jay_portrait": "img/jay_portrait-current.webp",
  "karway_hero": "img/karway_hero.webp",
  "kindberry_hero": "img/kindberry_hero.webp",
  "minsa_top": "img/minsa_top.webp",
  "minsa_before-after": "img/minsa_before-after.webp",
  "minsa_components": "img/minsa_components.webp",
  "minsa_design-system": "img/minsa_design-system.webp",
  "minsa_device-research": "img/minsa_device-research.webp",
  "minsa_final-flow": "img/minsa_final-flow.webp",
  "minsa_final-mockups": "img/minsa_final-mockups.webp",
  "minsa_hero": "img/minsa_hero.webp",
  "minsa_old-app": "img/minsa_old-app.webp",
  "minsa_old-ui": "img/minsa_old-ui.webp",
  "minsa_process": "img/minsa_process.webp",
  "minsa_prototype": "img/minsa_prototype.webp",
  "minsa_real-world": "img/minsa_real-world.webp",
  "minsa_taskflow": "img/minsa_taskflow.webp",
  "minsa_wireframes": "img/minsa_wireframes.webp",
  "pablo_hero": "img/pablo_hero.webp",
  "rodrigo": "img/rodrigo.webp",
  "solangie": "img/solangie.webp",
  "willington": "img/willington.webp"
};
const CV = { es: "cv/CV_JayFarfan_ES.pdf?v=3d0590316731", en: "cv/CV_JayFarfan_EN.pdf?v=28bd43a7d8f8" };

/* Image surfaces follow each asset, independently of the site theme. */
const IMAGE_BACKGROUNDS = {
  "diners_confidential": "#20252D",
  "pablo_dashboard": "#E8E6F0",
  "pablo_hallazgos": "#000000",
  "pablo_vistas": "#E9E6F4",
  "certezia_arquetipos": "#EAE7E5",
  "certezia_bmcs": "#252529",
  "certezia_preguntas": "#191919",
  "certezia_errores": "#B6B6B6",
  "certezia_uikit": "#EEEDF7",
  "certezia_tam-sam-som": "#151314",
  "certezia_flujo-final": "#EEEFF1",
  "certezia_flujo-redisenado": "#282828",
  "certezia_hero": "#E8E5F1",
  "certezia_problema": "#E4E8E5",
  "certezia_vista-prototipo": "#505050",
  "certezia_vista-testing": "#E6EBEF",
  "karway_hero": "#E8EDE6",
  "kindberry_hero": "#EEECE2",
  "minsa_top": "#E1E9EC",
  "minsa_before-after": "#E1E9EC",
  "minsa_components": "#D4DFE2",
  "minsa_design-system": "#E3EBEF",
  "minsa_device-research": "#E5EBEF",
  "minsa_final-flow": "#FFFFFF",
  "minsa_final-mockups": "#E1E9EC",
  "minsa_hero": "#E1E9EC",
  "minsa_old-app": "#E9EDEC",
  "minsa_old-ui": "#E0EDEA",
  "minsa_process": "#FFFFFF",
  "minsa_prototype": "#E5E5E5",
  "minsa_real-world": "#EEEAE6",
  "minsa_taskflow": "#FFFFFF",
  "minsa_wireframes": "#EDF3F3",
  "pablo_hero": "#E9E6F4"
};

const IMG_SIZE = {"diners_confidential": [1586, 992], "pablo_dashboard": [1280, 639], "pablo_hallazgos": [2048, 1152], "pablo_vistas": [2019, 2048], "certezia_arquetipos": [2047, 1246], "certezia_bmcs": [2048, 799], "certezia_preguntas": [1342, 785], "certezia_errores": [2048, 1664], "certezia_uikit": [2048, 839], "certezia_tam-sam-som": [2048, 1152], "certezia_flujo-final": [1920, 611], "certezia_flujo-redisenado": [1400, 372], "certezia_hero": [1400, 912], "certezia_problema": [1400, 878], "certezia_vista-prototipo": [1400, 1149], "certezia_vista-testing": [1400, 849], "eliana": [400, 400], "jay_portrait": [1254, 1254], "karway_hero": [1400, 910], "kindberry_hero": [1400, 974], "minsa_top": [1360, 1082], "minsa_before-after": [1400, 910], "minsa_components": [1227, 1920], "minsa_design-system": [1400, 1469], "minsa_device-research": [1263, 1920], "minsa_final-flow": [1400, 723], "minsa_final-mockups": [1400, 1114], "minsa_hero": [1400, 1006], "minsa_old-app": [1400, 1120], "minsa_old-ui": [1400, 678], "minsa_process": [1400, 430], "minsa_prototype": [1400, 1151], "minsa_real-world": [1400, 1300], "minsa_taskflow": [1400, 861], "minsa_wireframes": [1400, 784], "pablo_hero": [1400, 1044], "rodrigo": [400, 400], "solangie": [400, 400], "willington": [400, 400]};
