/* ===== PROCESO + IA · doble diamante ===== */
const STAGES = [
  { n: "01", name: x("Entender", "Understand"), sub: x("Abrir el problema", "Open the problem"),
    what: x("Empiezo hablando con usuarios, revisando datos y entendiendo cómo funciona hoy el producto. También necesito conocer las restricciones de negocio y tecnología antes de proponer una solución.", "I start by talking to users, reviewing data and understanding how the product works today. I also need to know the business and technology constraints before proposing a solution."),
    ai: x("Claude me ayuda a ordenar entrevistas, detectar temas recurrentes y preparar síntesis. Después reviso los hallazgos y vuelvo a las fuentes antes de convertirlos en decisiones.", "Claude helps me organize interviews, spot recurring themes and prepare syntheses. Then I review the findings and go back to the sources before turning them into decisions."),
    me: x("Qué investigar, con quién hablar y qué señales realmente importan.", "What to research, who to talk to and which signals really matter."),
    ev: [["diners", x("17 entrevistas, 50+ fricciones", "17 interviews, 50+ frictions")], ["certezia", x("Benchmark de 6 referentes", "Benchmark of 6 references")]] },
  { n: "02", name: x("Enfocar", "Focus"), sub: x("Cerrar el problema", "Close the problem"),
    what: x("Con la información suficiente, intento convertir todo lo aprendido en un problema concreto. Priorizo qué resolver ahora, qué dejar fuera y cómo sabremos si la solución funciona.", "With enough information, I try to turn everything I’ve learned into a concrete problem. I prioritize what to solve now, what to leave out and how we’ll know the solution works."),
    ai: x("La uso para comparar patrones, ordenar escenarios y explorar distintas formas de estructurar la información.", "I use it to compare patterns, organize scenarios and explore different ways of structuring information."),
    me: x("La prioridad, el alcance y qué entra realmente en la primera versión.", "The priority, the scope and what really goes into the first version."),
    ev: [["certezia", x("Arquetipos y alcance del Release 1", "Archetypes and Release 1 scope")], ["karway", x("Roadmap", "Roadmap")]] },
  { n: "03", name: x("Explorar", "Explore"), sub: x("Abrir la solución", "Open the solution"),
    what: x("Pruebo distintas maneras de resolver el problema antes de comprometerme con una sola. Trabajo con flujos, wireframes y prototipos hasta encontrar una dirección que tenga sentido para usuarios y equipo.", "I try different ways of solving the problem before committing to one. I work with flows, wireframes and prototypes until I find a direction that makes sense for users and the team."),
    ai: x("Uso Claude Design y ChatGPT Sites para probar ideas rápidamente y Lookback Eureka AI para acelerar la revisión de sesiones de testing.", "I use Claude Design and ChatGPT Sites to test ideas quickly and Lookback Eureka AI to speed up the review of testing sessions."),
    me: x("Qué ideas vale la pena probar, con quién probarlas y cuándo tenemos suficiente evidencia para avanzar.", "Which ideas are worth testing, with whom, and when we have enough evidence to move forward."),
    ev: [["certezia", x("5 sesiones · NPS 8/10", "5 sessions · NPS 8/10")], ["pablo", x("Conversación, dashboard y landing", "Conversation, dashboard and landing")]] },
  { n: "04", name: x("Construir", "Build"), sub: x("Cerrar la solución", "Close the solution"),
    what: x("Cuando la dirección está clara, trabajo con desarrollo para convertirla en producto: estados, casos límite, comportamiento responsive y detalles que suelen aparecer cuando una pantalla deja de ser un prototipo.", "Once the direction is clear, I work with engineering to turn it into a product: states, edge cases, responsive behavior and the details that tend to show up when a screen stops being a prototype."),
    ai: x("Claude Design y ChatGPT Sites me sirven para construir prototipos funcionales y sitios que permiten discutir una idea con algo más cercano al producto real.", "Claude Design and ChatGPT Sites help me build functional prototypes and websites, so we can discuss an idea with something closer to the real product."),
    me: x("Qué se especifica, qué puede simplificarse y cuándo una restricción técnica obliga a revisar el diseño.", "What gets specified, what can be simplified and when a technical constraint means the design needs another look."),
    ev: [["certezia", x("24 preguntas técnicas", "24 technical questions")], ["minsa", x("Design System escalable", "Scalable Design System")]] }
];
const DIAMONDS = [
  { h: x("Diamante 1 · Entender el problema", "Diamond 1 · Understand the problem"), s: [STAGES[0], STAGES[1]] },
  { h: x("Diamante 2 · Construir la solución", "Diamond 2 · Build the solution"), s: [STAGES[2], STAGES[3]] }
];

const SKILLS = [
  { h: x("Estrategia de producto", "Product strategy"), s: [x("Pensamiento sistémico", "Systems thinking"), "Product discovery", x("Priorización (MoSCoW)", "Prioritisation (MoSCoW)"), "Roadmap", x("Definición de MVP", "MVP definition"), x("Alineación negocio-usuario", "Business–user alignment")], ev: ["certezia", "karway"] },
  { h: x("Research", "Research"), s: [x("Entrevistas y trabajo de campo", "Interviews and fieldwork"), "Usability testing", "Journey mapping", "Benchmarking", x("Arquetipos", "Archetypes"), x("Priorización de insights", "Insight prioritisation")], ev: ["diners", "certezia"] },
  { h: x("UX / UI", "UX / UI"), s: ["User flows", x("Arquitectura de información", "Information architecture"), x("Prototipos de alta fidelidad", "High-fidelity prototypes"), "Design Systems", x("Accesibilidad", "Accessibility"), x("Contexto de uso", "Context of use"), "UX Writing"], ev: ["minsa", "certezia"] },
  { h: x("Colaboración con ingeniería", "Working with engineering"), s: [x("Estados y casos límite", "States and edge cases"), x("Handoff con desarrollo", "Handoff with engineering"), x("Diseño bajo restricciones", "Design within constraints"), x("Preguntas técnicas antes de decidir", "Technical questions before deciding"), "Agile / Scrum", x("Facilitación de talleres", "Workshop facilitation")], ev: ["certezia", "diners"] },
  { h: x("IA aplicada al diseño", "AI applied to design"), s: ["Claude", "ChatGPT", "Claude Design", "ChatGPT Sites", "Lookback Eureka AI", x("Síntesis y prototipado asistidos", "Assisted synthesis and prototyping")], tool: true, ev: ["certezia", "diners"] },
  { h: x("Base técnica", "Technical base"), s: ["HTML", "CSS", x("JavaScript básico", "Basic JavaScript"), "Git/GitHub", "Figma: components, Auto Layout, handoff"], ev: ["certezia"] }
];

function stageCell(s) {
  return `<div class="cell"><div class="n">${s.n} · ${t(s.sub)}</div><h4>${t(s.name)}</h4><p>${t(s.what)}</p><div class="lbl">${tx("Dónde uso IA", "Where I use AI")}</div><p>${t(s.ai)}</p><div class="lbl">${tx("Lo que decido yo", "What I decide")}</div><p>${t(s.me)}</p><div class="cell-reference"><div class="lbl">${tx("Evidencia", "Evidence")}</div><div class="ev">${s.ev.map((e) => caseLink(e[0], t(e[1]))).join(" · ")}</div></div></div>`;
}

function viewProcess() {
  const diamonds = DIAMONDS.map((d) => `<div class="ddg"><div class="ddh">${t(d.h)}</div><div class="grid c2">${d.s.map(stageCell).join("")}</div></div>`).join("");
  const skills = SKILLS.map((g) => `<div class="cell"><h4>${t(g.h)}</h4><div class="chips">${g.s.map((k) => `<span class="tag${g.tool ? " tool" : ""}">${t(k)}</span>`).join("")}</div><div class="cell-reference"><div class="lbl">${tx("En proyectos como", "In projects like")}</div><div class="ev">${g.ev.map((k) => caseLink(k, plain(t(byslug(k).client)).split(" · ")[0])).join(" · ")}</div></div></div>`).join("");
  return `<section class="sec first"><div class="wrap"><div class="eyebrow dash">${tx("Proceso + IA", "Process + AI")}</div><h1 class="hl balance process-title" style="margin-top:1rem">${tx("<span class=\"title-line\">Antes de diseñar, necesito entender</span> <span class=\"title-line\">qué problema estamos resolviendo.</span>", "<span class=\"title-line\">Before designing, I need to understand</span> <span class=\"title-line\">which problem we’re solving.</span>")}</h1><div class="process-intro"><p class="lead">${tx("Antes de dedicarme al <span class=\"soft-emphasis\">Diseño de productos digitales</span> trabajé varios años como Ingeniero Civil. De esa etapa me traje tres formas de trabajar: pensar en cómo se conecta un sistema, diseñar dentro de límites reales y prestar atención a cómo las personas lo usan.", "Before moving into <span class=\"soft-emphasis\">digital product design</span>, I worked for several years as a Civil Engineer. That experience shaped three ways of working: thinking about how a system connects, designing within real constraints and paying attention to how people use it.")}</p><p class="lead">${tx("Hoy las aplico al diseño: organizo información y flujos, priorizo soluciones viables con desarrollo y considero el contexto de uso y la accesibilidad desde el inicio.", "Today I apply them to design: I organize information and flows, prioritize feasible solutions with engineering and consider the context of use and accessibility from the start.")}</p></div></div></section>
  <section class="sec"><div class="wrap"><div class="shead"><div><div class="eyebrow dash">${tx("Doble diamante", "Double diamond")}</div><h2 class="hl balance" style="margin-top:1rem">${tx("Cómo diseño, etapa por etapa", "How I design, stage by stage")}</h2></div><div class="diamond-intro"><p>${tx("Uso el doble diamante como una referencia, no como una receta.", "I use the double diamond as a reference, not a recipe.")}</p><p>${tx("Algunos proyectos requieren más research, otros más iteración con desarrollo.", "Some projects need more research, others more iteration with engineering.")}</p><p>${tx("Lo importante para mí es separar dos momentos: entender bien el problema y luego explorar cómo resolverlo.", "What matters to me is separating two moments: understanding the problem well, and then exploring how to solve it.")}</p></div></div><div class="dd">${diamonds}</div></div></section>
  <section class="sec"><div class="wrap"><div class="crit"><div class="eyebrow dash">${tx("Cómo uso la IA", "How I use AI")}</div><h2 class="hl balance" style="margin-top:1rem">${tx("Uso IA para avanzar más rápido, no para que decida por mí.", "I use AI to move faster, not to let it decide for me.")}</h2><p class="big">${tx("La uso para ordenar research, explorar alternativas, resumir información y construir prototipos con más velocidad. Pero no tomo un resultado de IA como evidencia: vuelvo a los datos, lo contrasto con usuarios y con el equipo y decido qué tiene sentido conservar.", "I use it to organize research, explore alternatives, summarize information and build prototypes faster. But I don’t take an AI result as evidence: I go back to the data, check it with users and the team and decide what makes sense to keep.")}</p></div></div></section>
  <section class="sec"><div class="wrap"><div class="shead"><div><div class="eyebrow dash">Skillset</div><h2 class="hl balance" style="margin-top:1rem">${tx("Lo que sé hacer", "What I do")}</h2></div><p>${tx("Trabajo principalmente entre research, estrategia de producto y diseño de interfaces. Según el proyecto, puedo moverme desde discovery hasta una solución lista para desarrollo.", "I work mainly across research, product strategy and interface design. Depending on the project, I can move from discovery to a solution ready for development.")}</p></div><div class="grid c3">${skills}</div></div></section>${contactBlock()}`;
}

/* ===== SOBRE MÍ ===== */
function viewAbout() {
  const princ = [
    [x("Pensar en el sistema", "Think in systems"), x("Conecto información, tareas y decisiones del usuario para diseñar el recorrido completo.", "I connect information, tasks and user decisions to design the complete journey.")],
    [x("Diseñar con restricciones reales", "Design within real constraints"), x("Con producto, negocio y desarrollo, priorizo lo viable sin perder de vista la experiencia.", "With product, business and engineering, I prioritize what is feasible while protecting the experience.")],
    [x("Diseñar para personas reales", "Design for real people"), x("Observo el uso real y las barreras para crear experiencias claras y accesibles.", "I observe real usage and barriers to create clear, accessible experiences.")],
    [x("Usar IA sin delegar el criterio", "Use AI without outsourcing judgment"), x("La uso para explorar y avanzar más rápido. Las decisiones las tomo con el equipo.", "I use it to explore and move faster. I make decisions together with the team.")]
  ];
  return `<section class="sec first"><div class="wrap"><div class="about-top"><div class="portrait"><img src="${img("jay_portrait")}" alt="Jay Farfán"${imageAttributes("jay_portrait", true)}></div><div><div class="eyebrow dash">${tx("Sobre mí", "About me")}</div><h1 class="hl balance" style="margin-top:1rem">${tx("Cambié de profesión. Conservé la forma de resolver problemas.", "I changed careers. I kept my approach to solving problems.")}</h1><div class="abt about-intro"><p>${tx("Soy peruano, vivo en Quito y trabajé varios años como <strong>Ingeniero Civil</strong>. Durante la pandemia empecé a aprender programación y encontré mi camino hacia el diseño de productos digitales.", "I’m Peruvian, based in Quito, and spent several years working as a <strong>Civil Engineer</strong>. During the pandemic, I started learning programming and found my way into digital product design.")}</p><p>${tx("De la ingeniería me traje tres formas de mirar los problemas: <strong>pensamiento sistémico</strong>, <strong>diseño bajo restricciones</strong> y <strong>atención a las personas</strong>. Hoy las aplico para conectar información y flujos, tomar decisiones viables y crear experiencias accesibles.", "Engineering gave me three ways to approach problems: <strong>systems thinking</strong>, <strong>design within constraints</strong> and <strong>attention to people</strong>. Today, I apply them to connect information and flows, make feasible decisions and create accessible experiences.")}</p><p>${tx("Antes de diseñar, observo cómo las personas usan el producto y alineo sus necesidades con el negocio y las posibilidades del equipo. Hoy soy cofundador de DIGITAL-HUMANS y trabajo en fintech, govtech y marketplaces entre Perú y Ecuador.", "Before designing, I observe how people use the product and align their needs with business goals and what the team can build. Today, I’m a cofounder of DIGITAL-HUMANS, working across fintech, govtech and marketplaces in Peru and Ecuador.")}</p></div><div class="btns">${cvBtn("btn p")}<a class="btn s" href="#/work">${tx("Ver experiencia", "View experience")} →</a></div></div></div></div></section>
  <section class="sec"><div class="wrap"><div class="shead"><div><div class="eyebrow dash">${tx("Principios", "Principles")}</div><h2 class="hl balance" style="margin-top:1rem">${tx("Cómo trabajo", "How I work")}</h2></div><p>${tx("Cada proyecto es un reto distinto. En todos los casos, estos principios guían mis decisiones de Diseño.", "Every project is a different challenge. In every case, these principles guide my design decisions.")}</p></div><div class="grid c4">${princ.map((p, i) => `<div class="cell"><div class="n">0${i + 1}</div><h4>${t(p[0])}</h4><p>${t(p[1])}</p></div>`).join("")}</div></div></section>
  <section class="sec"><div class="wrap"><div class="shead"><div><div class="eyebrow dash">${tx("Fuera del trabajo", "Outside work")}</div><h2 class="hl balance" style="margin-top:1rem">${tx("Lo que hago cuando cierro Figma", "What I do when I close Figma")}</h2></div><div class="jama"><p>${tx("Soy peruano y vivo en Quito, así que buena parte de mi tiempo fuera del trabajo gira alrededor de la comida. Me gusta cocinar, probar restaurantes y encontrar lugares que me recuerden a Perú. 🇵🇪", "I’m Peruvian and live in Quito, so much of my time outside work revolves around food. I enjoy cooking, trying restaurants and finding places that remind me of Peru. 🇵🇪")}</p><p>${tx("Cuando viajo, busco dónde comen los locales, pruebo algo nuevo y casi siempre termino comparándolo con algún plato peruano. 🍽️", "When I travel, I look for where locals eat, try something new and almost always end up comparing it with a Peruvian dish. 🍽️")}</p><p>${tx("De ahí salió una idea que quiero desarrollar algún día: <strong>Jama</strong>, un directorio de restaurantes peruanos en el extranjero. Quiero ayudar a otros peruanos y a cualquiera con ganas de comer bien a encontrar lugares que realmente valgan la pena.", "That inspired an idea I want to build someday: <strong>Jama</strong>, a directory of Peruvian restaurants abroad. I want to help other Peruvians, and anyone looking for a good meal, find places that are truly worth visiting.")}</p><p>${tx("Por ahora sigue siendo un proyecto personal. Pero ya tiene nombre, así que algo de compromiso hay. 😄", "For now, it’s still a personal project. But it already has a name, so there’s at least some commitment. 😄")}</p></div></div></div></section>${quotesSection()}${contactBlock()}`;
}
function viewNotFound() { return `<section class="sec first"><div class="wrap"><div class="eyebrow">404</div><h1 class="hl" style="margin-top:1rem">${tx("Esta página no existe", "This page doesn’t exist")}</h1><div class="btns"><a class="btn p" href="#/work">${tx("Ver experiencia", "See experience")}</a></div></div></section>`; }
